name: array-api-tests-pytorch
channels:
  - conda-forge
  - pytorch-nightly
dependencies:
  # array-api-tests
  - python>=3.8
  - pytest
  - hypothesis
  - numpy>=1.22
  # pytorch
  - pytorch
  - cpuonly
